sudo: required

services:
  - docker

language: python
python:
  - "2.7"

# Run our own couchdb because Travis CI version ia too old (1.6)
before_install:
- docker pull couchdb:latest
- docker run -d --name couchdb -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass couchdb:latest
- docker ps -a

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - curl -X GET http://localhost:5984/
  - curl -X PUT http://admin:pass@localhost:5984/test

# command to run tests
script: nosetests

after_success:
  - codecov
